name: first-workflow
on: push
  
jobs:
  job1:
    name: job1name
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo 'hi'
      - name: yellow
        run: echo 'bie'
        
  job2:
    name: job2name
    runs-on: windows-latest
    steps:
      - name: hostname run
        run: hostname
      - name: wrirte
        run: echo 'hello'
        shell: pwsh
  job3:
    name: job3name
    needs: [job1,job2]
    runs-on: macos-latest
    steps:
      - name: hostname run
        run: hostname
      - name: wrirte
        run: echo 'hello'
  
 
